# Generated by Django 4.0.2 on 2022-03-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Condractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=20)),
                ('Photo', models.FileField(upload_to='Worksgallery/')),
                ('prevoius', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Condractor.previouswork')),
            ],
        ),
    ]
