# Generated by Django 4.0.2 on 2022-03-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0010_newlandlord_newlandlor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageLands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=30)),
                ('Photo', models.FileField(upload_to='ManageLand/')),
                ('Rate', models.CharField(max_length=10)),
                ('Pincode', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.district')),
                ('Landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newlandlord')),
            ],
        ),
    ]
