# Generated by Django 4.0.2 on 2022-03-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0002_landfacilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=20)),
                ('Photo', models.FileField(upload_to='Landgallery/')),
                ('managelands', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landlord.managelands')),
            ],
        ),
    ]
