# Generated by Django 4.0.2 on 2022-03-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0003_landgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managelands',
            old_name='District',
            new_name='district',
        ),
    ]
