# Generated by Django 4.0.2 on 2022-03-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_workerprofile_newwrkr'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Photo', models.FileField(upload_to='Latestwork/')),
                ('latest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Worker.workerprofile')),
            ],
        ),
    ]
