# Generated by Django 4.0.2 on 2022-05-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_remove_newconstructor_construct_bookingstatus'),
        ('Admin', '0002_admin'),
        ('Worker', '0003_latestwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('Complaint_Date', models.DateTimeField(auto_now=True)),
                ('Complaintreply', models.CharField(default='No reply', max_length=200)),
                ('Complaint_Status', models.IntegerField(default=False)),
                ('complaint_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.complainttype')),
                ('worker', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newworker')),
            ],
        ),
    ]
