# Generated by Django 4.0.2 on 2022-03-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Experience', models.CharField(max_length=30)),
                ('Address', models.TextField(unique=True)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20, unique=True)),
                ('Repassword', models.CharField(max_length=20, unique=True)),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.place')),
            ],
        ),
        migrations.CreateModel(
            name='NewConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Address', models.TextField(unique=True)),
                ('Totalemployees', models.CharField(max_length=20)),
                ('Registeredname', models.CharField(max_length=20)),
                ('Licensenumber', models.CharField(max_length=20)),
                ('Proof1', models.FileField(upload_to='identityproof/')),
                ('Proof2', models.FileField(upload_to='identityproof/')),
                ('Password', models.CharField(max_length=20, unique=True)),
                ('construct_status', models.IntegerField(default=False)),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.place')),
            ],
        ),
    ]
