# Generated by Django 4.0.2 on 2022-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_newworker_newconstructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworker',
            name='Repassword',
        ),
        migrations.AlterField(
            model_name='newconstructor',
            name='Address',
            field=models.TextField(max_length=50),
        ),
    ]
