# Generated by Django 4.0.2 on 2022-03-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_remove_newworker_repassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newconstructor',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
