# Generated by Django 4.0.2 on 2022-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_newconstructor_proof1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newconstructor',
            name='Proof1',
            field=models.FileField(upload_to='identyprrof1/'),
        ),
    ]
