# Generated by Django 4.0.2 on 2022-03-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0008_alter_newconstructor_proof2'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLandlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Address', models.TextField(max_length=50)),
                ('Photo', models.FileField(upload_to='Landlordimage/')),
                ('Proof', models.FileField(upload_to='identyproofLandlord/')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20, unique=True)),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.place')),
            ],
        ),
    ]
