# Generated by Django 4.0.2 on 2022-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_newlandlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlandlord',
            name='Newlandlor_status',
            field=models.IntegerField(default=False),
        ),
    ]
