# Generated by Django 4.0.2 on 2022-04-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_newconstructor_construct_bookingstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newconstructor',
            name='construct_bookingstatus',
        ),
    ]
