# Generated by Django 4.0.2 on 2022-05-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_remove_newconstructor_construct_bookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworker',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
