# Generated by Django 4.0.2 on 2022-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_newworker_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworker',
            name='Proofworker',
            field=models.FileField(null=True, upload_to='identyworker/'),
        ),
    ]
