# Generated by Django 4.0.2 on 2022-05-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_admin'),
        ('Guest', '0014_newworker_proofworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworker',
            name='title',
        ),
        migrations.AddField(
            model_name='newworker',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.workcategory'),
        ),
        migrations.AlterField(
            model_name='newworker',
            name='Proofworker',
            field=models.FileField(null=True, upload_to='workeridenty/'),
        ),
    ]
