# Generated by Django 4.0.2 on 2022-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0015_remove_newworker_title_newworker_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworker',
            name='jobs',
        ),
        migrations.AddField(
            model_name='newworker',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newworker',
            name='Proofworker',
            field=models.FileField(null=True, upload_to='identyworker/'),
        ),
    ]
