# Generated by Django 4.0.2 on 2022-03-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0010_newlandlord_newlandlor_status'),
        ('Landlord', '0004_rename_district_managelands_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_Date', models.DateField(auto_now=True)),
                ('b_status', models.IntegerField(default=False)),
                ('p_status', models.IntegerField(default=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newuser')),
                ('manageland', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landlord.managelands')),
            ],
        ),
    ]
