# Generated by Django 4.0.2 on 2022-03-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0004_rename_district_managelands_district'),
        ('Guest', '0010_newlandlord_newlandlor_status'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='LandBooking',
        ),
    ]
