# Generated by Django 4.0.2 on 2022-03-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_newlandlord_newlandlor_status'),
        ('User', '0002_rename_token_landbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='newworkerbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking2_Date', models.DateField(auto_now=True)),
                ('b2_status', models.IntegerField(default=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newuser')),
                ('newworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newworker')),
            ],
        ),
        migrations.CreateModel(
            name='constructorbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking1_Date', models.DateField(auto_now=True)),
                ('b1_status', models.IntegerField(default=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newuser')),
                ('newConstructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newconstructor')),
            ],
        ),
    ]
