# Generated by Django 4.0.2 on 2022-03-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_newworkerbooking_constructorbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructorbooking',
            old_name='User',
            new_name='User1',
        ),
    ]
