# Generated by Django 4.0.2 on 2022-04-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_user_newworkerbooking_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorbooking',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='constructorbooking',
            name='Details',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
