# Generated by Django 4.0.2 on 2022-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_constructorbooking_date_constructorbooking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkerbooking',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newworkerbooking',
            name='Details',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
