# Generated by Django 4.0.2 on 2022-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_newworkerbooking_date_newworkerbooking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newworkerbooking',
            name='Date',
            field=models.DateField(),
        ),
    ]
