# Generated by Django 4.0.2 on 2022-04-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0012_remove_newconstructor_construct_bookingstatus'),
        ('User', '0008_alter_newworkerbooking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=200)),
                ('Feedback_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=200)),
                ('Complaint_Date', models.DateTimeField(auto_now=True)),
                ('Complaintreply', models.CharField(default='No reply', max_length=200)),
                ('Complaint_Status', models.IntegerField(default=False)),
                ('Landlord', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newlandlord')),
                ('complaint_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.complainttype')),
                ('constructror', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newconstructor')),
                ('user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newuser')),
                ('worker', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newworker')),
            ],
        ),
    ]
