# Generated by Django 4.0.2 on 2022-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_feedback_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkerbooking',
            name='p_status',
            field=models.IntegerField(default=False),
        ),
    ]
