# Generated by Django 4.0.2 on 2022-05-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_newworkerbooking_p_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Complaint',
            new_name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='Landlord',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='constructror',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='worker',
        ),
    ]
