# Generated by Django 4.0.2 on 2022-05-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_newworker_title'),
        ('User', '0011_rename_complaint_complaint_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkerbooking',
            name='constructor1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.newconstructor'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaintreply',
            field=models.CharField(default='No reply', max_length=200, null=True),
        ),
    ]
