# Generated by Django 4.0.2 on 2022-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_newworkerbooking_constructor1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkerbooking',
            name='ContactDetails',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
