# Generated by Django 4.1.13 on 2024-01-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_newworkerbooking_contactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworkerbooking',
            name='ContactDetails',
        ),
    ]
